/* HSK 1 (classic 150-word list), grouped by theme. Sentences and dialogues are original.
   Same format as lessons.js; erhua syllables (nǎr, yìdiǎnr) take their 儿 with them. */
LESSONS.push(
  {
    course: "HSK 1", title: "Numbers",
    words: [
      { zh: "一", py: "yī", en: "one" }, { zh: "二", py: "èr", en: "two" }, { zh: "三", py: "sān", en: "three" },
      { zh: "四", py: "sì", en: "four" }, { zh: "五", py: "wǔ", en: "five" }, { zh: "六", py: "liù", en: "six" },
      { zh: "七", py: "qī", en: "seven" }, { zh: "八", py: "bā", en: "eight" }, { zh: "九", py: "jiǔ", en: "nine" },
      { zh: "十", py: "shí", en: "ten" }, { zh: "几", py: "jǐ", en: "how many (small numbers)" },
      { zh: "多少", py: "duō'shao", en: "how many / how much" },
    ],
    phrases: [
      { zh: "这个多少钱？", py: "zhè'ge duō'shao qián?", en: "How much is this?" },
      { zh: "十块。", py: "shí kuài.", en: "Ten yuan." },
      { zh: "我有三个朋友。", py: "wǒ yǒu sān ge péng'you.", en: "I have three friends." },
      { zh: "你的电话是多少？", py: "nǐ de diàn'huà shì duō'shao?", en: "What's your phone number?" },
    ],
    dialog: {
      scene: "Buying apples at the market",
      lines: [
        { who: "A", zh: "苹果多少钱？", py: "píng'guǒ duō'shao qián?", en: "How much are the apples?" },
        { who: "B", zh: "一个五块。", py: "yí ge wǔ kuài.", en: "Five yuan each." },
        { who: "A", zh: "我买三个。", py: "wǒ mǎi sān ge.", en: "I'll take three." },
        { who: "B", zh: "好，十五块。", py: "hǎo, shí'wǔ kuài.", en: "OK, fifteen yuan." },
        { who: "A", zh: "给你钱。", py: "gěi nǐ qián.", en: "Here's the money." },
        { who: "B", zh: "谢谢！", py: "xiè'xie!", en: "Thank you!" },
      ],
    },
  },
  {
    course: "HSK 1", title: "People",
    words: [
      { zh: "我", py: "wǒ", en: "I, me" }, { zh: "你", py: "nǐ", en: "you" }, { zh: "他", py: "tā", en: "he, him" },
      { zh: "她", py: "tā", en: "she, her" }, { zh: "我们", py: "wǒ'men", en: "we, us" }, { zh: "人", py: "rén", en: "person" },
      { zh: "谁", py: "shéi", en: "who" }, { zh: "是", py: "shì", en: "to be" }, { zh: "朋友", py: "péng'you", en: "friend" },
      { zh: "同学", py: "tóng'xué", en: "classmate" }, { zh: "老师", py: "lǎo'shī", en: "teacher" },
      { zh: "学生", py: "xué'sheng", en: "student" },
    ],
    phrases: [
      { zh: "他是谁？", py: "tā shì shéi?", en: "Who is he?" },
      { zh: "她是我的朋友。", py: "tā shì wǒ de péng'you.", en: "She is my friend." },
      { zh: "你是老师吗？", py: "nǐ shì lǎo'shī ma?", en: "Are you a teacher?" },
      { zh: "不是，我是学生。", py: "bú shì, wǒ shì xué'sheng.", en: "No, I'm a student." },
      { zh: "我们是同学。", py: "wǒ'men shì tóng'xué.", en: "We are classmates." },
    ],
    dialog: {
      scene: "Who's that?",
      lines: [
        { who: "A", zh: "那个人是谁？", py: "nà'ge rén shì shéi?", en: "Who is that person?" },
        { who: "B", zh: "他是我的老师。", py: "tā shì wǒ de lǎo'shī.", en: "He's my teacher." },
        { who: "A", zh: "她也是老师吗？", py: "tā yě shì lǎo'shī ma?", en: "Is she a teacher too?" },
        { who: "B", zh: "不是，她是我的同学。", py: "bú shì, tā shì wǒ de tóng'xué.", en: "No, she's my classmate." },
        { who: "A", zh: "你们都是学生吗？", py: "nǐ'men dōu shì xué'sheng ma?", en: "Are you all students?" },
        { who: "B", zh: "是的。", py: "shì de.", en: "Yes." },
      ],
    },
  },
  {
    course: "HSK 1", title: "Family & pets",
    words: [
      { zh: "爸爸", py: "bà'ba", en: "dad" }, { zh: "妈妈", py: "mā'ma", en: "mum" }, { zh: "儿子", py: "ér'zi", en: "son" },
      { zh: "女儿", py: "nǚ'ér", en: "daughter" }, { zh: "家", py: "jiā", en: "home, family" },
      { zh: "岁", py: "suì", en: "years old" }, { zh: "爱", py: "ài", en: "to love" }, { zh: "狗", py: "gǒu", en: "dog" },
      { zh: "猫", py: "māo", en: "cat" },
    ],
    phrases: [
      { zh: "我爱我的家。", py: "wǒ ài wǒ de jiā.", en: "I love my family." },
      { zh: "你家有几口人？", py: "nǐ jiā yǒu jǐ kǒu rén?", en: "How many people are in your family?" },
      { zh: "我有一个儿子。", py: "wǒ yǒu yí ge ér'zi.", en: "I have a son." },
      { zh: "你女儿几岁了？", py: "nǐ nǚ'ér jǐ suì le?", en: "How old is your daughter?" },
      { zh: "我家有一只猫。", py: "wǒ jiā yǒu yì zhī māo.", en: "We have a cat." },
    ],
    dialog: {
      scene: "Looking at family photos",
      lines: [
        { who: "A", zh: "这是你爸爸吗？", py: "zhè shì nǐ bà'ba ma?", en: "Is this your dad?" },
        { who: "B", zh: "是，这是我爸爸和妈妈。", py: "shì, zhè shì wǒ bà'ba hé mā'ma.", en: "Yes, this is my dad and mum." },
        { who: "A", zh: "你家有狗吗？", py: "nǐ jiā yǒu gǒu ma?", en: "Do you have a dog?" },
        { who: "B", zh: "没有，我们有两只猫。", py: "méi'yǒu, wǒ'men yǒu liǎng zhī māo.", en: "No, we have two cats." },
        { who: "A", zh: "我爱猫！", py: "wǒ ài māo!", en: "I love cats!" },
      ],
    },
  },
  {
    course: "HSK 1", title: "Language",
    words: [
      { zh: "中国", py: "Zhōng'guó", en: "China" }, { zh: "北京", py: "Běi'jīng", en: "Beijing" },
      { zh: "汉语", py: "Hàn'yǔ", en: "Chinese (language)" }, { zh: "字", py: "zì", en: "character" },
      { zh: "说", py: "shuō", en: "to speak" }, { zh: "读", py: "dú", en: "to read (aloud)" }, { zh: "写", py: "xiě", en: "to write" },
      { zh: "听", py: "tīng", en: "to listen" }, { zh: "会", py: "huì", en: "can (know how to)" },
      { zh: "能", py: "néng", en: "can (be able to)" },
    ],
    phrases: [
      { zh: "你会说汉语吗？", py: "nǐ huì shuō Hàn'yǔ ma?", en: "Can you speak Chinese?" },
      { zh: "我会说一点儿。", py: "wǒ huì shuō yì'diǎnr.", en: "I can speak a little." },
      { zh: "这个字怎么读？", py: "zhè'ge zì zěn'me dú?", en: "How do you read this character?" },
      { zh: "请再说一次。", py: "qǐng zài shuō yí cì.", en: "Please say it again." },
      { zh: "他在北京工作。", py: "tā zài Běi'jīng gōng'zuò.", en: "He works in Beijing." },
    ],
    dialog: {
      scene: "Chatting after a Chinese class",
      lines: [
        { who: "A", zh: "你会写汉字吗？", py: "nǐ huì xiě Hàn'zì ma?", en: "Can you write Chinese characters?" },
        { who: "B", zh: "不会，我只会说。", py: "bú huì, wǒ zhǐ huì shuō.", en: "No, I can only speak." },
        { who: "A", zh: "你说得很好！", py: "nǐ shuō de hěn hǎo!", en: "You speak very well!" },
        { who: "B", zh: "谢谢，我爱人是中国人。", py: "xiè'xie, wǒ ài'ren shì Zhōng'guó rén.", en: "Thanks — my spouse is Chinese." },
        { who: "A", zh: "你能读这个字吗？", py: "nǐ néng dú zhè'ge zì ma?", en: "Can you read this character?" },
        { who: "B", zh: "对不起，我不会读。", py: "duì'bu'qǐ, wǒ bú huì dú.", en: "Sorry, I can't read it." },
      ],
    },
  },
  {
    course: "HSK 1", title: "Dates & time",
    words: [
      { zh: "今天", py: "jīn'tiān", en: "today" }, { zh: "明天", py: "míng'tiān", en: "tomorrow" },
      { zh: "昨天", py: "zuó'tiān", en: "yesterday" }, { zh: "年", py: "nián", en: "year" }, { zh: "月", py: "yuè", en: "month" },
      { zh: "号", py: "hào", en: "day of the month" }, { zh: "星期", py: "xīng'qī", en: "week" },
      { zh: "点", py: "diǎn", en: "o'clock" }, { zh: "分钟", py: "fēn'zhōng", en: "minute" },
      { zh: "现在", py: "xiàn'zài", en: "now" }, { zh: "时候", py: "shí'hou", en: "time, when" },
    ],
    phrases: [
      { zh: "今天几月几号？", py: "jīn'tiān jǐ yuè jǐ hào?", en: "What's the date today?" },
      { zh: "今天星期几？", py: "jīn'tiān xīng'qī jǐ?", en: "What day of the week is it?" },
      { zh: "现在几点？", py: "xiàn'zài jǐ diǎn?", en: "What time is it?" },
      { zh: "现在三点十分。", py: "xiàn'zài sān diǎn shí fēn.", en: "It's ten past three." },
      { zh: "你什么时候回家？", py: "nǐ shén'me shí'hou huí jiā?", en: "When are you going home?" },
    ],
    dialog: {
      scene: "Making plans",
      lines: [
        { who: "A", zh: "明天是星期六吗？", py: "míng'tiān shì xīng'qī'liù ma?", en: "Is tomorrow Saturday?" },
        { who: "B", zh: "不是，明天星期五。", py: "bú shì, míng'tiān xīng'qī'wǔ.", en: "No, tomorrow is Friday." },
        { who: "A", zh: "我们星期六几点见？", py: "wǒ'men xīng'qī'liù jǐ diǎn jiàn?", en: "What time shall we meet on Saturday?" },
        { who: "B", zh: "上午十点，好吗？", py: "shàng'wǔ shí diǎn, hǎo ma?", en: "Ten in the morning, OK?" },
        { who: "A", zh: "好的，星期六见！", py: "hǎo de, xīng'qī'liù jiàn!", en: "OK, see you Saturday!" },
      ],
    },
  },
  {
    course: "HSK 1", title: "Daily routine",
    words: [
      { zh: "上午", py: "shàng'wǔ", en: "morning" }, { zh: "中午", py: "zhōng'wǔ", en: "noon" },
      { zh: "下午", py: "xià'wǔ", en: "afternoon" }, { zh: "睡觉", py: "shuì'jiào", en: "to sleep" },
      { zh: "工作", py: "gōng'zuò", en: "to work; job" }, { zh: "学习", py: "xué'xí", en: "to study" },
      { zh: "做", py: "zuò", en: "to do, to make" }, { zh: "回", py: "huí", en: "to return" },
      { zh: "来", py: "lái", en: "to come" }, { zh: "去", py: "qù", en: "to go" },
    ],
    phrases: [
      { zh: "你做什么工作？", py: "nǐ zuò shén'me gōng'zuò?", en: "What do you do for work?" },
      { zh: "我上午工作，下午学习。", py: "wǒ shàng'wǔ gōng'zuò, xià'wǔ xué'xí.", en: "I work in the morning and study in the afternoon." },
      { zh: "你几点睡觉？", py: "nǐ jǐ diǎn shuì'jiào?", en: "What time do you go to bed?" },
      { zh: "我中午回家。", py: "wǒ zhōng'wǔ huí jiā.", en: "I go home at noon." },
      { zh: "你明天来吗？", py: "nǐ míng'tiān lái ma?", en: "Are you coming tomorrow?" },
    ],
    dialog: {
      scene: "After work",
      lines: [
        { who: "A", zh: "你去哪儿？", py: "nǐ qù nǎr?", en: "Where are you going?" },
        { who: "B", zh: "我回家。你呢？", py: "wǒ huí jiā. nǐ ne?", en: "Home. And you?" },
        { who: "A", zh: "我去学校学习。", py: "wǒ qù xué'xiào xué'xí.", en: "I'm going to school to study." },
        { who: "B", zh: "你下午不工作吗？", py: "nǐ xià'wǔ bù gōng'zuò ma?", en: "Don't you work in the afternoon?" },
        { who: "A", zh: "不工作，我上午工作。", py: "bù gōng'zuò, wǒ shàng'wǔ gōng'zuò.", en: "No, I work in the mornings." },
      ],
    },
  },
  {
    course: "HSK 1", title: "Food & drink",
    words: [
      { zh: "吃", py: "chī", en: "to eat" }, { zh: "喝", py: "hē", en: "to drink" }, { zh: "菜", py: "cài", en: "dish, vegetable" },
      { zh: "米饭", py: "mǐ'fàn", en: "cooked rice" }, { zh: "水", py: "shuǐ", en: "water" }, { zh: "茶", py: "chá", en: "tea" },
      { zh: "苹果", py: "píng'guǒ", en: "apple" }, { zh: "水果", py: "shuǐ'guǒ", en: "fruit" },
      { zh: "杯子", py: "bēi'zi", en: "cup, glass" }, { zh: "饭店", py: "fàn'diàn", en: "restaurant" },
    ],
    phrases: [
      { zh: "你想吃什么？", py: "nǐ xiǎng chī shén'me?", en: "What would you like to eat?" },
      { zh: "我想喝茶。", py: "wǒ xiǎng hē chá.", en: "I'd like some tea." },
      { zh: "请给我一杯水。", py: "qǐng gěi wǒ yì bēi shuǐ.", en: "A glass of water, please." },
      { zh: "这个菜很好吃。", py: "zhè'ge cài hěn hǎo'chī.", en: "This dish is delicious." },
      { zh: "我喜欢吃水果。", py: "wǒ xǐ'huan chī shuǐ'guǒ.", en: "I like eating fruit." },
    ],
    dialog: {
      scene: "Ordering at a restaurant",
      lines: [
        { who: "A", zh: "你们想吃什么？", py: "nǐ'men xiǎng chī shén'me?", en: "What would you like to eat?" },
        { who: "B", zh: "我们要两个菜和米饭。", py: "wǒ'men yào liǎng ge cài hé mǐ'fàn.", en: "We'll have two dishes and rice." },
        { who: "A", zh: "喝什么？", py: "hē shén'me?", en: "Anything to drink?" },
        { who: "B", zh: "两杯茶，谢谢。", py: "liǎng bēi chá, xiè'xie.", en: "Two cups of tea, thanks." },
        { who: "A", zh: "好的，请等一下。", py: "hǎo de, qǐng děng yí'xià.", en: "OK, one moment please." },
        { who: "B", zh: "这个饭店的菜很好吃！", py: "zhè'ge fàn'diàn de cài hěn hǎo'chī!", en: "The food here is delicious!" },
      ],
    },
  },
  {
    course: "HSK 1", title: "Shopping",
    words: [
      { zh: "买", py: "mǎi", en: "to buy" }, { zh: "钱", py: "qián", en: "money" }, { zh: "块", py: "kuài", en: "yuan (spoken)" },
      { zh: "商店", py: "shāng'diàn", en: "shop" }, { zh: "东西", py: "dōng'xi", en: "thing, stuff" },
      { zh: "衣服", py: "yī'fu", en: "clothes" }, { zh: "些", py: "xiē", en: "some" },
      { zh: "个", py: "gè", en: "general measure word" }, { zh: "本", py: "běn", en: "measure word for books" },
      { zh: "书", py: "shū", en: "book" },
    ],
    phrases: [
      { zh: "你想买什么？", py: "nǐ xiǎng mǎi shén'me?", en: "What do you want to buy?" },
      { zh: "我想买一些东西。", py: "wǒ xiǎng mǎi yì'xiē dōng'xi.", en: "I want to buy a few things." },
      { zh: "这本书多少钱？", py: "zhè běn shū duō'shao qián?", en: "How much is this book?" },
      { zh: "太贵了！", py: "tài guì le!", en: "Too expensive!" },
      { zh: "这件衣服很漂亮。", py: "zhè jiàn yī'fu hěn piào'liang.", en: "This piece of clothing is very pretty." },
    ],
    dialog: {
      scene: "In a clothes shop",
      lines: [
        { who: "A", zh: "你好，我想买衣服。", py: "nǐ hǎo, wǒ xiǎng mǎi yī'fu.", en: "Hello, I'd like to buy some clothes." },
        { who: "B", zh: "这件怎么样？", py: "zhè jiàn zěn'me'yàng?", en: "How about this one?" },
        { who: "A", zh: "很漂亮！多少钱？", py: "hěn piào'liang! duō'shao qián?", en: "Very pretty! How much?" },
        { who: "B", zh: "一百块。", py: "yì bǎi kuài.", en: "A hundred yuan." },
        { who: "A", zh: "太贵了。八十块，行吗？", py: "tài guì le. bā'shí kuài, xíng ma?", en: "Too expensive. Would eighty be OK?" },
        { who: "B", zh: "好，八十块。", py: "hǎo, bā'shí kuài.", en: "OK, eighty." },
      ],
    },
  },
  {
    course: "HSK 1", title: "Places & directions",
    words: [
      { zh: "在", py: "zài", en: "at, in; to be (somewhere)" }, { zh: "哪", py: "nǎ", en: "which" },
      { zh: "哪儿", py: "nǎr", en: "where" }, { zh: "这", py: "zhè", en: "this" }, { zh: "那", py: "nà", en: "that" },
      { zh: "里", py: "lǐ", en: "inside" }, { zh: "上", py: "shàng", en: "on, above" }, { zh: "下", py: "xià", en: "under, below" },
      { zh: "前面", py: "qián'miàn", en: "in front" }, { zh: "后面", py: "hòu'miàn", en: "behind" },
      { zh: "学校", py: "xué'xiào", en: "school" }, { zh: "医院", py: "yī'yuàn", en: "hospital" },
      { zh: "医生", py: "yī'shēng", en: "doctor" },
    ],
    phrases: [
      { zh: "你在哪儿？", py: "nǐ zài nǎr?", en: "Where are you?" },
      { zh: "我在学校。", py: "wǒ zài xué'xiào.", en: "I'm at school." },
      { zh: "医院在哪儿？", py: "yī'yuàn zài nǎr?", en: "Where is the hospital?" },
      { zh: "医院在学校后面。", py: "yī'yuàn zài xué'xiào hòu'miàn.", en: "The hospital is behind the school." },
      { zh: "书在桌子上。", py: "shū zài zhuō'zi shang.", en: "The book is on the table." },
    ],
    dialog: {
      scene: "Asking the way",
      lines: [
        { who: "A", zh: "请问，医院在哪儿？", py: "qǐng'wèn, yī'yuàn zài nǎr?", en: "Excuse me, where is the hospital?" },
        { who: "B", zh: "在那个商店后面。", py: "zài nà'ge shāng'diàn hòu'miàn.", en: "Behind that shop." },
        { who: "A", zh: "在学校前面吗？", py: "zài xué'xiào qián'miàn ma?", en: "In front of the school?" },
        { who: "B", zh: "对。你去看医生吗？", py: "duì. nǐ qù kàn yī'shēng ma?", en: "Right. Are you going to see a doctor?" },
        { who: "A", zh: "不是，我妈妈在医院工作。", py: "bú shì, wǒ mā'ma zài yī'yuàn gōng'zuò.", en: "No, my mum works at the hospital." },
      ],
    },
  },
  {
    course: "HSK 1", title: "Getting around & phoning",
    words: [
      { zh: "出租车", py: "chū'zū'chē", en: "taxi" }, { zh: "飞机", py: "fēi'jī", en: "plane" },
      { zh: "坐", py: "zuò", en: "to sit; to take (transport)" }, { zh: "开", py: "kāi", en: "to drive; to open" },
      { zh: "住", py: "zhù", en: "to live, to stay" }, { zh: "打电话", py: "dǎ diàn'huà", en: "to make a phone call" },
      { zh: "喂", py: "wèi", en: "hello? (on the phone; often also said wéi)" },
    ],
    phrases: [
      { zh: "我们坐出租车去吧。", py: "wǒ'men zuò chū'zū'chē qù ba.", en: "Let's take a taxi." },
      { zh: "你住在哪儿？", py: "nǐ zhù zài nǎr?", en: "Where do you live?" },
      { zh: "我坐飞机去北京。", py: "wǒ zuò fēi'jī qù Běi'jīng.", en: "I'm flying to Beijing." },
      { zh: "他会开车。", py: "tā huì kāi chē.", en: "He can drive." },
      { zh: "我给你打电话。", py: "wǒ gěi nǐ dǎ diàn'huà.", en: "I'll give you a call." },
    ],
    dialog: {
      scene: "A phone call",
      lines: [
        { who: "A", zh: "喂，你好！你在哪儿？", py: "wèi, nǐ hǎo! nǐ zài nǎr?", en: "Hello! Where are you?" },
        { who: "B", zh: "我在出租车上。", py: "wǒ zài chū'zū'chē shang.", en: "I'm in a taxi." },
        { who: "A", zh: "你几点到？", py: "nǐ jǐ diǎn dào?", en: "What time will you get here?" },
        { who: "B", zh: "十分钟以后。", py: "shí fēn'zhōng yǐ'hòu.", en: "In ten minutes." },
        { who: "A", zh: "好，我在饭店前面等你。", py: "hǎo, wǒ zài fàn'diàn qián'miàn děng nǐ.", en: "OK, I'll wait for you in front of the restaurant." },
        { who: "B", zh: "好的，一会儿见！", py: "hǎo de, yí'huìr jiàn!", en: "OK, see you soon!" },
      ],
    },
  },
  {
    course: "HSK 1", title: "Weather",
    words: [
      { zh: "天气", py: "tiān'qì", en: "weather" }, { zh: "冷", py: "lěng", en: "cold" }, { zh: "热", py: "rè", en: "hot" },
      { zh: "下雨", py: "xià yǔ", en: "to rain" }, { zh: "大", py: "dà", en: "big" }, { zh: "小", py: "xiǎo", en: "small" },
      { zh: "多", py: "duō", en: "many, much" }, { zh: "少", py: "shǎo", en: "few, little" }, { zh: "很", py: "hěn", en: "very" },
      { zh: "太", py: "tài", en: "too, extremely" }, { zh: "漂亮", py: "piào'liang", en: "pretty, beautiful" },
    ],
    phrases: [
      { zh: "今天天气怎么样？", py: "jīn'tiān tiān'qì zěn'me'yàng?", en: "How's the weather today?" },
      { zh: "今天很热。", py: "jīn'tiān hěn rè.", en: "It's hot today." },
      { zh: "明天会下雨。", py: "míng'tiān huì xià yǔ.", en: "It will rain tomorrow." },
      { zh: "北京冬天很冷。", py: "Běi'jīng dōng'tiān hěn lěng.", en: "Winters in Beijing are very cold." },
      { zh: "你的家很大！", py: "nǐ de jiā hěn dà!", en: "Your home is big!" },
    ],
    dialog: {
      scene: "Talking about the weekend weather",
      lines: [
        { who: "A", zh: "今天天气太热了！", py: "jīn'tiān tiān'qì tài rè le!", en: "It's far too hot today!" },
        { who: "B", zh: "是啊，明天会冷一点儿吗？", py: "shì a, míng'tiān huì lěng yì'diǎnr ma?", en: "Yes! Will it be a bit cooler tomorrow?" },
        { who: "A", zh: "明天下雨。", py: "míng'tiān xià yǔ.", en: "It'll rain tomorrow." },
        { who: "B", zh: "那我们在家看电影吧！", py: "nà wǒ'men zài jiā kàn diàn'yǐng ba!", en: "Then let's watch a film at home!" },
        { who: "A", zh: "好主意！", py: "hǎo zhǔ'yi!", en: "Good idea!" },
      ],
    },
  },
  {
    course: "HSK 1", title: "At home",
    words: [
      { zh: "电脑", py: "diàn'nǎo", en: "computer" }, { zh: "电视", py: "diàn'shì", en: "TV" },
      { zh: "电影", py: "diàn'yǐng", en: "film, movie" }, { zh: "桌子", py: "zhuō'zi", en: "table" },
      { zh: "椅子", py: "yǐ'zi", en: "chair" }, { zh: "看", py: "kàn", en: "to look, watch, read" },
      { zh: "看见", py: "kàn'jiàn", en: "to see" },
    ],
    phrases: [
      { zh: "你喜欢看电影吗？", py: "nǐ xǐ'huan kàn diàn'yǐng ma?", en: "Do you like watching films?" },
      { zh: "我的电脑在桌子上。", py: "wǒ de diàn'nǎo zài zhuō'zi shang.", en: "My computer is on the table." },
      { zh: "你看见我的猫了吗？", py: "nǐ kàn'jiàn wǒ de māo le ma?", en: "Have you seen my cat?" },
      { zh: "猫在椅子下面。", py: "māo zài yǐ'zi xià'mian.", en: "The cat is under the chair." },
      { zh: "我们看电视吧。", py: "wǒ'men kàn diàn'shì ba.", en: "Let's watch TV." },
    ],
    dialog: {
      scene: "An evening at home",
      lines: [
        { who: "A", zh: "你在做什么？", py: "nǐ zài zuò shén'me?", en: "What are you doing?" },
        { who: "B", zh: "我在看电视。你呢？", py: "wǒ zài kàn diàn'shì. nǐ ne?", en: "I'm watching TV. And you?" },
        { who: "A", zh: "我在用电脑工作。", py: "wǒ zài yòng diàn'nǎo gōng'zuò.", en: "I'm working on the computer." },
        { who: "B", zh: "现在十点了，睡觉吧！", py: "xiàn'zài shí diǎn le, shuì'jiào ba!", en: "It's ten o'clock — time for bed!" },
        { who: "A", zh: "好的，晚安！", py: "hǎo de, wǎn'ān!", en: "OK, good night!" },
      ],
    },
  },
  {
    course: "HSK 1", title: "Likes & wants",
    words: [
      { zh: "喜欢", py: "xǐ'huan", en: "to like" }, { zh: "想", py: "xiǎng", en: "to want, would like; to think" },
      { zh: "高兴", py: "gāo'xìng", en: "happy, glad" }, { zh: "好", py: "hǎo", en: "good" },
      { zh: "怎么", py: "zěn'me", en: "how" }, { zh: "怎么样", py: "zěn'me'yàng", en: "how about it? how is it?" },
      { zh: "什么", py: "shén'me", en: "what" },
    ],
    phrases: [
      { zh: "你喜欢什么？", py: "nǐ xǐ'huan shén'me?", en: "What do you like?" },
      { zh: "我喜欢狗，不喜欢猫。", py: "wǒ xǐ'huan gǒu, bù xǐ'huan māo.", en: "I like dogs, not cats." },
      { zh: "我很高兴。", py: "wǒ hěn gāo'xìng.", en: "I'm very happy." },
      { zh: "这个怎么说？", py: "zhè'ge zěn'me shuō?", en: "How do you say this?" },
      { zh: "我们去饭店，怎么样？", py: "wǒ'men qù fàn'diàn, zěn'me'yàng?", en: "Let's go to a restaurant — how about it?" },
    ],
    dialog: {
      scene: "Weekend plans",
      lines: [
        { who: "A", zh: "星期天你想做什么？", py: "xīng'qī'tiān nǐ xiǎng zuò shén'me?", en: "What do you want to do on Sunday?" },
        { who: "B", zh: "我想去看电影。", py: "wǒ xiǎng qù kàn diàn'yǐng.", en: "I want to go and see a film." },
        { who: "A", zh: "你喜欢什么电影？", py: "nǐ xǐ'huan shén'me diàn'yǐng?", en: "What films do you like?" },
        { who: "B", zh: "中国电影。你呢？", py: "Zhōng'guó diàn'yǐng. nǐ ne?", en: "Chinese films. And you?" },
        { who: "A", zh: "我也喜欢！我们一起去，怎么样？", py: "wǒ yě xǐ'huan! wǒ'men yì'qǐ qù, zěn'me'yàng?", en: "Me too! Shall we go together?" },
        { who: "B", zh: "好啊，我很高兴！", py: "hǎo a, wǒ hěn gāo'xìng!", en: "Great, I'd love to!" },
      ],
    },
  },
  {
    course: "HSK 1", title: "Polite phrases & names",
    words: [
      { zh: "请", py: "qǐng", en: "please" }, { zh: "谢谢", py: "xiè'xie", en: "thank you" },
      { zh: "不客气", py: "bú kè'qi", en: "you're welcome" }, { zh: "对不起", py: "duì'bu'qǐ", en: "sorry" },
      { zh: "没关系", py: "méi guān'xi", en: "it doesn't matter" }, { zh: "再见", py: "zài'jiàn", en: "goodbye" },
      { zh: "先生", py: "xiān'sheng", en: "Mr., sir" }, { zh: "小姐", py: "xiǎo'jiě", en: "Miss, Ms." },
      { zh: "叫", py: "jiào", en: "to be called" }, { zh: "名字", py: "míng'zi", en: "name" },
      { zh: "认识", py: "rèn'shi", en: "to know (a person)" },
    ],
    phrases: [
      { zh: "对不起，我来晚了。", py: "duì'bu'qǐ, wǒ lái wǎn le.", en: "Sorry, I'm late." },
      { zh: "没关系。", py: "méi guān'xi.", en: "It doesn't matter." },
      { zh: "请问，您叫什么名字？", py: "qǐng'wèn, nín jiào shén'me míng'zi?", en: "Excuse me, what's your name?" },
      { zh: "王先生，您好！", py: "Wáng xiān'sheng, nín hǎo!", en: "Hello, Mr Wang!" },
      { zh: "认识你很高兴。", py: "rèn'shi nǐ hěn gāo'xìng.", en: "It's nice to meet you." },
    ],
    dialog: {
      scene: "A business meeting",
      lines: [
        { who: "A", zh: "您好，请问您是李先生吗？", py: "nín hǎo, qǐng'wèn nín shì Lǐ xiān'sheng ma?", en: "Hello — excuse me, are you Mr Li?" },
        { who: "B", zh: "是，我是。您是？", py: "shì, wǒ shì. nín shì?", en: "Yes, I am. And you are?" },
        { who: "A", zh: "我叫马克。对不起，我来晚了。", py: "wǒ jiào Mǎ'kè. duì'bu'qǐ, wǒ lái wǎn le.", en: "I'm Mark. Sorry I'm late." },
        { who: "B", zh: "没关系。请坐！", py: "méi guān'xi. qǐng zuò!", en: "No problem. Please sit down!" },
        { who: "A", zh: "谢谢！", py: "xiè'xie!", en: "Thank you!" },
        { who: "B", zh: "不客气。", py: "bú kè'qi.", en: "You're welcome." },
      ],
    },
  },
  {
    course: "HSK 1", title: "Little grammar words",
    words: [
      { zh: "的", py: "de", en: "possessive particle ('s)" }, { zh: "了", py: "le", en: "particle: done / change" },
      { zh: "吗", py: "ma", en: "question particle" }, { zh: "呢", py: "ne", en: "particle: and…? what about…?" },
      { zh: "不", py: "bù", en: "not" }, { zh: "没有", py: "méi'yǒu", en: "not have; didn't" },
      { zh: "有", py: "yǒu", en: "to have; there is" }, { zh: "都", py: "dōu", en: "all, both" },
      { zh: "和", py: "hé", en: "and, with" }, { zh: "一点儿", py: "yì'diǎnr", en: "a little" },
    ],
    phrases: [
      { zh: "这是我的书。", py: "zhè shì wǒ de shū.", en: "This is my book." },
      { zh: "我吃饭了。", py: "wǒ chī fàn le.", en: "I've eaten." },
      { zh: "我没有钱。", py: "wǒ méi'yǒu qián.", en: "I don't have any money." },
      { zh: "我们都是朋友。", py: "wǒ'men dōu shì péng'you.", en: "We are all friends." },
      { zh: "我和你都喜欢茶。", py: "wǒ hé nǐ dōu xǐ'huan chá.", en: "You and I both like tea." },
    ],
    dialog: {
      scene: "Lunchtime",
      lines: [
        { who: "A", zh: "你吃饭了吗？", py: "nǐ chī fàn le ma?", en: "Have you eaten?" },
        { who: "B", zh: "还没有。你呢？", py: "hái méi'yǒu. nǐ ne?", en: "Not yet. You?" },
        { who: "A", zh: "我吃了一点儿水果。", py: "wǒ chī le yì'diǎnr shuǐ'guǒ.", en: "I had a little fruit." },
        { who: "B", zh: "我们一起去吃饭吧！", py: "wǒ'men yì'qǐ qù chī fàn ba!", en: "Let's go and eat together!" },
        { who: "A", zh: "好！你想吃米饭和菜吗？", py: "hǎo! nǐ xiǎng chī mǐ'fàn hé cài ma?", en: "OK! Do you want rice and some dishes?" },
      ],
    },
  },
);
