/* Generated by tools/set-login.js — salted hash only, no password stored. */
var LOGIN = {"salt":"af4c93b20779346c2ba9a5e2fa93f1e8","hash":"9164b6b2b4d5705b40989d26bf50b10b9fa13e94045262eb378a8da2ba9f918f","iterations":600000};
