/* Pre-renders all lesson audio with macOS voices. Run from the app folder: node tools/build_audio.js
   Needs: macOS `say` with the Tingting voice, and ffmpeg. Only Tingting can be rendered to a file on macOS,
   so Person 2 is Tingting shifted ~4 semitones lower (tone shapes are preserved). */
const fs = require("fs"), path = require("path"), vm = require("vm"), crypto = require("crypto");
const { execFileSync } = require("child_process");

const root = path.join(__dirname, "..");
const ctx = { console };
vm.createContext(ctx);
const src = ["lessons.js", "tone-engine.js"].map(f => fs.readFileSync(path.join(root, f), "utf8")).join("\n");
vm.runInContext(src + "\nthis.LESSONS = LESSONS; this.parsePinyin = parsePinyin;", ctx);

const VOICE = { A: "Tingting", B: "TingtingLow" };
const FILTER = { Tingting: [], TingtingLow: ["-af", "asetrate=22050*0.79,aresample=22050,atempo=1.266"] };
const jobs = new Map();
const add = (voice, text) => jobs.set(`${voice}|${text}`, { voice, text });

function addItem(item, who) {
  const voice = VOICE[who === "B" ? "B" : "A"];
  add(voice, item.zh);
  const parsed = ctx.parsePinyin(item.py), chars = [...item.zh.replace(/[\p{P}\s]/gu, "")];
  if (chars.length !== parsed.syls.length) { console.warn("mismatch:", item.zh); return; }
  for (const w of parsed.words) {
    if (!w.syls.length) continue;
    add(voice, chars.slice(w.syls[0].idx, w.syls[w.syls.length - 1].idx + 1).join(""));
  }
}

ctx.LESSONS.forEach(L => {
  L.phrases.forEach(p => addItem(p));
  L.dialog.lines.forEach(l => addItem(l, l.who));
});
addItem({ zh: "妈麻马骂", py: "mā má mǎ mà" });

const outDir = path.join(root, "audio"), tmp = path.join(outDir, "_tmp.aiff");
fs.mkdirSync(outDir, { recursive: true });
const manifest = {};
let made = 0;
for (const [key, { voice, text }] of jobs) {
  const file = crypto.createHash("sha1").update(key).digest("hex").slice(0, 12) + ".m4a";
  manifest[key] = file;
  const dest = path.join(outDir, file);
  if (fs.existsSync(dest)) continue;
  execFileSync("say", ["-v", "Tingting", "-o", tmp, text]);
  execFileSync("ffmpeg", ["-y", "-loglevel", "error", "-i", tmp, ...FILTER[voice], "-ac", "1", "-c:a", "aac", "-b:a", "40k", dest]);
  if (fs.statSync(dest).size < 2000) throw new Error(`Silent clip for "${text}" (${voice}) — check the Tingting voice is installed`);
  made++;
}
if (fs.existsSync(tmp)) fs.unlinkSync(tmp);
const used = new Set(Object.values(manifest));
for (const f of fs.readdirSync(outDir)) if (f.endsWith(".m4a") && !used.has(f)) fs.unlinkSync(path.join(outDir, f));
fs.writeFileSync(path.join(outDir, "manifest.js"), "/* Generated by tools/build_audio.js */\nvar AUDIO_FILES = " + JSON.stringify(manifest, null, 0) + ";\n");
console.log(`${jobs.size} clips (${made} new) → audio/`);
