/* Sets the app login. Run from the app folder:  node tools/set-login.js
   Asks for a username + password (hidden), writes only a salted PBKDF2 hash to login.js,
   then commits and pushes so the published app checks against it. */
const fs = require("fs"), path = require("path"), crypto = require("crypto");
const { execFileSync } = require("child_process");

const ITERATIONS = 600000;

function ask(question, hidden) {
  return new Promise(resolve => {
    process.stdout.write(question);
    const stdin = process.stdin;
    let input = "";
    stdin.setRawMode && stdin.setRawMode(true);
    stdin.resume();
    stdin.setEncoding("utf8");
    const onData = ch => {
      if (ch === "\r" || ch === "\n") {
        stdin.setRawMode && stdin.setRawMode(false);
        stdin.pause();
        stdin.removeListener("data", onData);
        process.stdout.write("\n");
        resolve(input);
      } else if (ch === "\u0003") {
        process.exit(1);
      } else if (ch === "\u007f") {
        input = input.slice(0, -1);
      } else {
        input += ch;
        if (!hidden) process.stdout.write(ch);
      }
    };
    stdin.on("data", onData);
  });
}

(async () => {
  const user = (await ask("Username: ", false)).trim();
  const pw = await ask("Password (hidden): ", true);
  const pw2 = await ask("Repeat password: ", true);
  if (!user || pw.length < 8) { console.error("Need a username and a password of at least 8 characters."); process.exit(1); }
  if (pw !== pw2) { console.error("Passwords don't match."); process.exit(1); }
  const salt = crypto.randomBytes(16).toString("hex");
  const hash = crypto.pbkdf2Sync(pw, `${salt}|${user.toLowerCase()}`, ITERATIONS, 32, "sha256").toString("hex");
  const root = path.join(__dirname, "..");
  fs.writeFileSync(path.join(root, "login.js"),
    `/* Generated by tools/set-login.js — salted hash only, no password stored. */\nvar LOGIN = ${JSON.stringify({ salt, hash, iterations: ITERATIONS })};\n`);
  console.log("Saved login.js");
  if (process.argv.includes("--no-push")) return;
  try {
    execFileSync("git", ["add", "login.js"], { cwd: root, stdio: "inherit" });
    execFileSync("git", ["commit", "-m", "Update app login"], { cwd: root, stdio: "inherit" });
    execFileSync("git", ["push"], { cwd: root, stdio: "inherit" });
    console.log("Published — the web app now checks this login (allow ~1 minute for GitHub Pages).");
  } catch (e) {
    console.error("Saved locally, but publishing failed — run: git add login.js && git commit -m login && git push");
  }
})();
