/* Sets the app login. Run from the app folder:  node tools/set-login.js
   Asks for a username + password (hidden), writes only a salted PBKDF2 hash to login.js,
   then commits and pushes so the published app checks against it.
   Test a login without changing it:  node tools/set-login.js --check */
const fs = require("fs"), path = require("path"), crypto = require("crypto");
const { execFileSync } = require("child_process");

const ITERATIONS = 600000;
/* Must match normalize() in auth.js: phone keyboards turn quotes/dashes "smart". */
const normalize = s => s.normalize("NFC").replace(/[‘’]/g, "'").replace(/[“”]/g, '"').replace(/[–—]/g, "-");

function ask(question, hidden) {
  return new Promise(resolve => {
    process.stdout.write(question);
    const stdin = process.stdin;
    let input = "";
    stdin.setRawMode && stdin.setRawMode(true);
    stdin.resume();
    stdin.setEncoding("utf8");
    const onData = chunk => {
      const text = chunk.replace(/\x1b\[[0-9;]*[A-Za-z~]/g, ""); // drop arrow keys etc.
      for (const ch of text) {
        if (ch === "\r" || ch === "\n") {
          stdin.setRawMode && stdin.setRawMode(false);
          stdin.pause();
          stdin.removeListener("data", onData);
          process.stdout.write(hidden ? `  (${input.length} characters)\n` : "\n");
          return resolve(input);
        }
        if (ch === "\u0003") process.exit(1);
        if (ch === "\u007f" || ch === "\b") input = input.slice(0, -1);
        else if (ch >= " ") { input += ch; if (!hidden) process.stdout.write(ch); }
      }
    };
    stdin.on("data", onData);
  });
}

const derive = (user, pw, salt, iterations) =>
  crypto.pbkdf2Sync(normalize(pw), `${salt}|${normalize(user.trim()).toLowerCase()}`, iterations, 32, "sha256").toString("hex");

(async () => {
  const root = path.join(__dirname, "..");
  if (process.argv.includes("--check")) {
    const src = fs.readFileSync(path.join(root, "login.js"), "utf8");
    const cfg = JSON.parse(src.match(/LOGIN = (\{.*\});/)[1]);
    const user = await ask("Username: ", false), pw = await ask("Password (hidden): ", true);
    console.log(derive(user, pw, cfg.salt, cfg.iterations) === cfg.hash ? "✓ Correct — this login works." : "✗ Does not match the saved login.");
    return;
  }
  const user = (await ask("Username: ", false)).trim();
  const pw = await ask("Password (hidden): ", true);
  const pw2 = await ask("Repeat password: ", true);
  if (!user || pw.length < 8) { console.error("Need a username and a password of at least 8 characters."); process.exit(1); }
  if (pw !== pw2) { console.error("Passwords don't match."); process.exit(1); }
  const salt = crypto.randomBytes(16).toString("hex");
  const hash = derive(user, pw, salt, ITERATIONS);
  fs.writeFileSync(path.join(root, "login.js"),
    `/* Generated by tools/set-login.js — salted hash only, no password stored. */\nvar LOGIN = ${JSON.stringify({ salt, hash, iterations: ITERATIONS })};\n`);
  console.log("Saved login.js");
  if (process.argv.includes("--no-push")) return;
  try {
    execFileSync("git", ["add", "login.js"], { cwd: root, stdio: "inherit" });
    execFileSync("git", ["commit", "-m", "Update app login"], { cwd: root, stdio: "inherit" });
    execFileSync("git", ["push"], { cwd: root, stdio: "inherit" });
    console.log("Published — the web app now checks this login (allow ~1 minute for GitHub Pages).");
  } catch (e) {
    console.error("Saved locally, but publishing failed — run: git add login.js && git commit -m login && git push");
  }
})();
